version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    # environment:
    #    KEYCLOAK_ADMIN: admin
    #    KEYCLOAK_ADMIN_PASSWORD: admin
    #    KC_PROXY: edge
    #    KC_HOSTNAME_STRICT: false
    #    KC_HTTP_ENABLED: true
    #    KC_DB: postgres
    #    KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_test
    #    KC_DB_USERNAME: keycloak_test
    #    KC_DB_PASSWORD: keycloak_test
    env_file:
      - .env
    volumes:
      - ./themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: keycloak_test
      POSTGRES_PASSWORD: keycloak_test
      POSTGRES_DB: keycloak_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: